### ISSUE TITLE
Missing FlexOTube Texture

### ISSUE THREAD

**Issue by cdcrockett** [BobPalmer/MKS-LITE#1]
I kept getting an error in game that the texture for the Flex-O-Tube was missing. Verified the path in the CFG file for the part and found that it was, as reported, missing. Grabbed the version from the MKS (full) repository. Issue corrected.

**Comment by RyanW1019** [comment]
After 0.0.2 released Sat 10/3, I no longer get the error when loading parts with Flex-O-Tube. May be able to close this issue.
