### ISSUE TITLE
OSE Integration is missing an override for the stock lab's workshop

### ISSUE THREAD

**Issue by timmersuk** [BobPalmer/MKS-LITE#15]
OSE.cfg overrides the other OSE parts from MaterialKits to RocketParts, however it's missing the stock lab.

I think the config should be :- 

@PART[Large_Crewed_Lab]:NEEDS[Workshop]	//Convert the lab over to RocketParts
{  
 -MODULE[OseModuleWorkshop] {}
 -MODULE[OseModuleRecycler] {}
  MODULE
  {
    name = OseModuleWorkshop
    ConversionRate = 1.0 // How much of a parts mass needs to be processed until it is done
    ProductivityFactor = 0.1 // How much units of the resource a processed per second
    UpkeepResource = ElectricCharge // This resource will be consumed 1 per second during processing
    InputResource = RocketParts // This resource will be used to process the items
    MinimumCrew = 2 // Amount of Kerbals needed for the Workshop to work
    MaxPartVolume = 300.0
    Animate = true
  }
  
 -RESOURCE[MaterialKits]{}
	RESOURCE
	{
		name = RocketParts
		amount = 200
		maxAmount = 200
		isTweakable = true
	}  
}

**Comment by timmersuk** [comment]
Oops ... actually that also ought to have :AFTER[Workshop] as well ...

**Comment by BobPalmer** [comment]
Closing as MKS-L is moving to the OSE workflow
