### ISSUE TITLE
Inflatable modules remain crew-able and fully functional even when deflated.

### ISSUE THREAD

**Issue by fraz86** [BobPalmer/MKS-LITE#20]
'Scout' Habitation Module - when deflated, retains:
- crew capacity
- undiminished capacity for Supplies/Mulch/Organics/Fertilizer
- functional "Habitat" and "Recycler" converters

'Scout' Inflatable Workshop - when deflated, retains:
- crew capacity
- undiminished capacity for RocketParts
- functional OSE Workshop

'Scout' Agricultural Module - when deflated, retains:
- undiminished capacity for Organics/Fertilizer/Dirt
- functional "Agroponics" converter

**Comment by BobPalmer** [comment]
Resovled in next release
