### ISSUE TITLE
Stuck with thousands of RocketParts

### ISSUE THREAD

**Issue by Hbas** [BobPalmer/MKS-LITE#26]
When Extraplanetary Launchpads is present, RocketParts are replaced by a combination of SpecializedParts and MaterialKits in the resource chain. 

The issue, though, is that I'm not able to use the RocketParts already stored in my ships/stations/etc nor those created/transported using EL smelters + workshops.

Could you put a "RocketPart -> SpecializedParts + MaterialKits" conversion in all EL workshops?

**Comment by BobPalmer** [comment]
For now, the best bet would be to use HyperEdit's misc tools to adjust your resource quantities
