### ISSUE TITLE
extraplanetary launchpads parts not loading

### ISSUE THREAD

**Issue by Dr-Farnsworth** [BobPalmer/MKS-LITE#36]
extraplanetary launchpads orbital dock and launch pads are not loading when the current revision of MKS-LITE is installed.

 If I drop down to an older revision the issue goes away.

**Comment by Bear67** [comment]
That's cause that's the way he has it setup. If you want too change it, you'll have to modify the **EL_Parts.cfg** file in the Directory: _GameData\UmbraSpaceIndustries\Kolonization_

**Comment by Dawnkeeper** [comment]
But why? Being forbidden to build ships in space just because i could have colonies makes no sense.

**Comment by JimClonk** [comment]
I believe this is not intentional as the full UKS adds it's own launchpad while removing the default ones.
The Kolonization folder is the same in UKS and MKS-Lite, but MKS-Lite does not add it's own launchpads, so this was likely an oversight.
