### ISSUE TITLE
'Scout' Pod Re-entry mechanics seem inaccurate

### ISSUE THREAD

**Issue by MadMerlyn** [BobPalmer/MKS-LITE#50]
Basically.. I can stick a 1.25m heatshield on the bottom of the standard lander pod, which doesn't cover the entire base of the pod, and it can survive a 35km peri re-entry from minmus, the Scout pod however has a 1.25m attachment node, and even if I put a 2.5m shield on it, will still overheat and explode as if there is no heatshield attached to it at all. I don't know if it's the aero applying to the sides of the pod or what, maybe it's the yellow bars protruding through the heatshield?

**Comment by BobPalmer** [comment]
Very likely the latter.  Add a spacer.
