### ISSUE TITLE
Inflatables colliders and jumping bases

### ISSUE THREAD

**Issue by NyankoSensei** [BobPalmer/MKS-LITE#7]
Every time i load scenario the base jump, i have solved at the moment by changing a bit connection nodes.
 

MKSL_jump_fix.cfg
@PART[MKSL_Lander] {
	@node_stack_pod01 = .85,-.145,0,  1,0,0,2
	@node_stack_pod02 = -.85,-.145,0, -1,0,0,2
	@node_stack_pod03 = 0,-.145,.85,  0,0,1,2
	@node_stack_pod04 = 0,-.145,-.85, 0,0,-1,2
}

@PART[MKSL_AnchorHub] {
	@node_stack_pod01 = .85,.005,0,  1,0,0,2
	@node_stack_pod02 = -.85,.005,0, -1,0,0,2
	@node_stack_pod03 = 0,.005,.85,  0,0,1,2
	@node_stack_pod04 = 0,.005,-.85, 0,0,-1,2

        // Better node placement on top
	@node_stack_top = 0,1,0,0,1,0,2
}

**Comment by BobPalmer** [comment]
Thanks!  Adding this in next release
