### ISSUE TITLE
Add antennarange support

### ISSUE THREAD

**Issue by NyankoSensei** [BobPalmer/MKS-LITE#8]
I have copy the file from UKS

MKS_Lite_Antennarange.cfg
@PART[MKSL_CommPak]:AFTER[KolonyTools]:NEEDS[AntennaRange]
{
	@MODULE[ModuleDataTransmitter]
	{
		@name = ModuleLimitedDataTransmitter
		nominalRange = 3150000000
		simpleRange = 18000000000
		maxPowerFactor = 4
		maxDataFactor = 8
	}
}

**Comment by BobPalmer** [comment]
Thanks as well!  This will be in the next update
